_target_: src.models.module.BaseModule
learning_rate: 0.01
weight_decay: 0.0005

net:
  _target_: src.models.components.nets.HierSCN
  in_channels_edges: ???
  in_channels_nodes: ???
  out_channels: ???
  hidden_channels: 64
  hidden_layers: 3
  kappa: 2
  pooling_type: none
  pooling_ratio: ???
  p_dropout: 0.3
  aggregate: True
